server:
  port: 8081

spring:
  application:
    name: blog-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      # 用来解决swagger3无法正常开启，更换匹配策略
      matching-strategy: ant_path_matcher
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
#  security:
#    user:
#      name: user
#      password: 111111

mybatis-plus:
  configuration:
    #用这个打印到日志里
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  #逻辑删除
#  global-config:
#    db-config:
#      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:/mapper/*.xml
# 配置日志级别，这个是log4j，不过这里不用，使用了logback
#logging:
#  level: debug
#  file:
#    name:

# 自定义配置
xiaolei565:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h


#oss:
#  qiniu:
#    url: http://七牛云的外链域名
#    accessKey: 密钥AK
#    secretKey: 密钥SK
#    bucketName: 仓库名